export default {
  START_PLAYBACK: 'START_PLAYBACK',
  STOP_PLAYBACK: 'STOP_PLAYBACK',
  SET_ACTIVE_AUDIOCARD: 'SET_ACTIVE_AUDIOCARD',
  SET_ACTIVE_AUDIOCARD_AND_URI: 'SET_ACTIVE_AUDIOCARD_AND_URI',
  SET_AUDIOCARDS: 'SET_AUDIOCARDS',
  SET_ACTIVE_URI: 'SET_ACTIVE_URI',
  SET_IS_ON_REPEAT: 'SET_IS_ON_REPEAT',
  SET_IS_ON_RANDOM: 'SET_IS_ON_RANDOM',
};
