export default {
  START_PLAYBACK: 'START_PLAYBACK',
  STOP_PLAYBACK: 'STOP_PLAYBACK',
  SET_ACTIVE_AUDIOCARD: 'SET_ACTIVE_AUDIOCARD',
  SET_AUDIOCARDS: 'SET_AUDIOCARDS',
  SET_ACTIVE_URI: 'SET_ACTIVE_URI',
};
