export default {
  ADD_FRONT_TEXT_WORD: 'ADD_FRONT_TEXT_WORD',
  ADD_BACK_TEXT_WORD: 'ADD_BACK_TEXT_WORD',
  REMOVE_FRONT_TEXT_WORD_AT_INDEX: 'REMOVE_FRONT_TEXT_WORD_AT_INDEX',
  REMOVE_BACK_TEXT_WORD_AT_INDEX: 'REMOVE_BACK_TEXT_WORD_AT_INDEX',
  SET_CARD_EDITING_STATUSES: 'SET_CARD_EDITING_STATUSES',
  CLEAR_CARD_EDITING: 'CLEAR_CARD_EDITING',
};
