export default {
  ADD_FRONT_TEXT_WORD: 'ADD_FRONT_TEXT_WORD',
  ADD_BACK_TEXT_WORD: 'ADD_BACK_TEXT_WORD',
  CLEAR_FRONT_TEXT_WORD: 'CLEAR_FRONT_TEXT_WORD',
  CLEAR_BACK_TEXT_WORD: 'CLEAR_BACK_TEXT_WORD',
};
